import 'dart:ui';

import 'package:montesori/config/color.dart';

class Huruf {
  static const List<String> title = [
    "Aa",
    "Bb",
    "Cc",
    "Dd",
    "Ee",
    "Ff",
    "Gg",
    "Hh",
    "Ii",
    "Jj",
    "Kk",
    "Ll",
    "Mm",
    "Nn",
    "Oo",
    "Pp",
    "Qq",
    "Rr",
    "Ss",
    "Tt",
  ];
  static const List<String> subTitle = [
    "Apel",
    "Bawang",
    "Cabai",
    "Durian",
    "Es Batu",
    "Foto",
    "Gurita",
    "Ham",
    "Ikan",
    "Jamur",
    "Kentang",
    "Lontong",
    "Madu",
    "Nasi",
    "Onde-onde",
    "Pisang",
    "Quiz",
    "Rambutan",
    "Susu",
    "Telur"
  ];
  static const List<String> imageUrl = [
    "assets/images/huruf/before/ic_huruf_a.png",
    "assets/images/huruf/before/ic_huruf_b.png",
    "assets/images/huruf/before/ic_huruf_c.png",
    "assets/images/huruf/before/ic_huruf_d.png",
    "assets/images/huruf/before/ic_huruf_e.png",
    "assets/images/huruf/before/ic_huruf_f.png",
    "assets/images/huruf/before/ic_huruf_g.png",
    "assets/images/huruf/before/ic_huruf_h.png",
    "assets/images/huruf/before/ic_huruf_i.png",
    "assets/images/huruf/before/ic_huruf_j.png",
    "assets/images/huruf/before/ic_huruf_k.png",
    "assets/images/huruf/before/ic_huruf_l.png",
    "assets/images/huruf/before/ic_huruf_m.png",
    "assets/images/huruf/before/ic_huruf_n.png",
    "assets/images/huruf/before/ic_huruf_o.png",
    "assets/images/huruf/before/ic_huruf_p.png",
    "assets/images/huruf/before/ic_huruf_q.png",
    "assets/images/huruf/before/ic_huruf_r.png",
    "assets/images/huruf/before/ic_huruf_s.png",
    "assets/images/huruf/before/ic_huruf_t.png",
  ];
  static const List<Color> colorBg = [
    ColorApps.hurufA,
    ColorApps.hurufB,
    ColorApps.hurufC,
    ColorApps.hurufD,
    ColorApps.hurufE,
    ColorApps.hurufF,
    ColorApps.hurufG,
    ColorApps.hurufH,
    ColorApps.hurufI,
    ColorApps.hurufJ,
    ColorApps.hurufK,
    ColorApps.hurufL,
    ColorApps.hurufM,
    ColorApps.hurufN,
    ColorApps.hurufO,
    ColorApps.hurufP,
    ColorApps.hurufQ,
    ColorApps.hurufR,
    ColorApps.hurufS,
    ColorApps.hurufT,
  ];
  static const List<Color> colorHuruf = [
    ColorApps.titleA,
    ColorApps.titleB,
    ColorApps.titleC,
    ColorApps.titleD,
    ColorApps.titleE,
    ColorApps.titleF,
    ColorApps.titleG,
    ColorApps.titleH,
    ColorApps.titleI,
    ColorApps.titleJ,
    ColorApps.titleK,
    ColorApps.titleL,
    ColorApps.titleM,
    ColorApps.titleN,
    ColorApps.titleO,
    ColorApps.titleP,
    ColorApps.titleQ,
    ColorApps.titleR,
    ColorApps.titleS,
    ColorApps.titleT,
  ];
}
